/* eslint-disable */
export const artistData = {
    date:"31st december 2024 • NEW YEAR’S EVE",
    place:'SURF BEACH at SUNWAY LAGOON',
    artist: "sarah landry",
    heroImageUrl: "./Landing-Page/Lineup/artist-image.webp",
    heroImageUrlMob1: "./Landing-Page/Lineup/artist-image-mob-1.webp",
    heroImageUrlMob2: "./Landing-Page/Lineup/artist-image-mob-2.webp",
    heading: "welcome home, ",
    spanText:"lavas!",
    text: "It’s time to turn up the heat once again because this year's Pinkfish Countdown is rocking a whole new look.",
    bannerHeading:'Grab Your TicketS & Enter the ',
    bannerHeadingSpan:"Future",
    bannerText:'Get ready to usher in the new year with electrifying beats! Take the countdown into a whole new dimension, where the future is now, and the music never stops.' ,
    bannerBtn1Text:"Buy Tickets",
    BannerBtn1Link:'#',
    bannerBtn2Text:"Learn More",
    BannerBtn2Link:'#',
    PurpleTicketIconUrl:'./Landing-Page/Icons/purple_ticket.png',
    BlackTicketIconUrl:'./Landing-Page/Icons/purple_ticket.png',
    imgList:["./Landing-Page/Socials/insta.webp",
        "./Landing-Page/Socials/yt.webp",
        "./Landing-Page/Socials/tiktok.webp",
        "./Landing-Page/Socials/fb.webp",
     ],
     links:[
        "https://www.instagram.com/pinkfishfestival/",
        "https://www.youtube.com/@Pinkfishfestival",
        "https://www.tiktok.com/@pinkfishfestival",
        "https://www.instagram.com/pinkfishfestival/",
     ],
     followPageHeading:'Want to Meet Your Favorite Artists?',
     followPageText1Part1:'Tag us when your festival package arrives, and you could unlock a',
     followPageText1SpanText:' Meet & Greet ',
     followPageText1Part2:'with the artists of your wildest dreams.',
     followPageText2:'Snap it, share it, and step into the spotlight for an unforgettable experience!',
     offerSectionHeading1:'Limited Time Offer:',
     offerSectionHeading2:'Get RM5 Off!',
     offerSectionTextPart1:'Use code ',
     offerSectionText1Span:'PFC24HD5',
     offerSectionTextPart2:' for an instant RM5 discount when you secure your spot in the rave of the century. The clock is ticking—don’t wait!',
     offerSectionSideImage:'./Landing-Page//OfferSection/social_side_img.webp',
     brandImg1:'./Landing-Page/Brands/brand_1.png',
     brandImg2:'./Landing-Page/Brands/brand_2.svg',
}